apiVersion: v1
kind: Pod
metadata:
  name: test-api
spec:
  containers:
    - image: docker.io/piggy09/test-api
      name: test-api
      imagePullPolicy: Always
      resources: {}
      ports:
        - containerPort: 8080